### ISSUE TITLE
Container/Pod whitelisting

### ISSUE THREAD

**Issue by dabeck** [sematext/logagent-js#191]
I've tried to accomplish a setup where I've disabled logging by default `LOGSENE_ENABLED_DEFAULT=false` and want to whitelist several pods for logging to the logagent using the annotation `sematext.com/logs-enabled=true`. Unfortunately the annotation is either ignored or has no effect on the logging behavior. 

The logagent still states: 
```
2020-02-17T14:39:29.264Z v3.0.14 pid[9] Container <containerid-omitted> /<name-omited> setting LOGSENE_ENABLED=false
```

Am I missing something or is this a bug?

**Comment by adnanrahic** [comment]
Hey @dabeck!

Can you try using `LOGS_ENABLED_DEFAULT=false` instead?

**Comment by dabeck** [comment]
OK, I just set the proposed settings but this doesn't seem to have any effect at all. Now every container in the cluster is logged. 

Or is this not possible via helm flag?
```
helm install st-agent --set logsToken=<token-omitted> --set infraToken=<token-omitted> --set region=US --set logagent.config.LOGS_ENABLED_DEFAULT=false --namespace sematext stable/sematext-agent 
```

**Comment by megastef** [comment]
I guess the problem is in the helm chart. I think it is not setting and environment variable for the logagent container. 

Please try: 
```
helm ... -set logagent.config.env.LOGS_ENABLED_DEFAULT=false
```
This might set the value in logagent config.env section, but i'm not sure.

**Comment by megastef** [comment]
CC: @hakman do you have any idea how to pass `LOGSENE_ENABLED_DEFAULT=false` via helm chart?

**Comment by hakman** [comment]
Please try:
`helm ... -set logagent.config.LOGSENE_ENABLED_DEFAULT=false`

**Comment by megastef** [comment]
It looks you have to use: 
```
helm install st-agent --set logsToken=<token-omitted> --set infraToken=<token-omitted> --set region=US --set logagent.config.LOGSENE_ENABLED_DEFAULT=false --namespace sematext stable/sematext-agent 
```


Do you see in Logagent start messages, if Logagent is loading plugin "kubernetes-enrichment"? Because the plugin is interpreting k8s annotations. 

In case the annotation is not working, could you please try to set `LOGS_ENABLED=true` env variable instead of `sematext.com/logs-enabled=true` pod annotation. 

We will check the annotations feature tomorrow.

**Comment by dabeck** [comment]
Just to be clear my setting with 
`--set logagent.config.LOGSENE_ENABLED_DEFAULT=false` worked as expected,
`--set logagent.config.LOGS_ENABLED_DEFAULT=false` did not.

But the k8s annotation did not work as expected. The agent does indeed log that „kubernetes-enrichment“ was enabled. I‘ll try the env var configuration tomorrow. 

I‘ve already tested another configuration with setting the `LOGS_ENABLED: „true“` k8s-label on the pod but this did just enable logging for the k8s-POD-meta container and not the running container itself.

**Comment by dabeck** [comment]
*UPDATE:* Setting the container env-var `LOGS_ENABLED=true` did NOT work.

**Comment by megastef** [comment]
Could you please provide details about your environment?
Kubernetes version, Docker version or cri-o version cloud platform, logagent version.

**Comment by dabeck** [comment]
Cloud platform: OpenStack
K8s: rke (Rancher Kubernetes Engine) deployed k8s Cluster v1.14.9
Docker: 18.06.3-ce
Logagent: sematext/logagent:latest (3.0.14)

**Comment by dabeck** [comment]
Do you have any new findings on this?

**Comment by megastef** [comment]
Hi @dabeck - thanks for reporting, we are working on it. We assume that logs get disabled on docker level, before Kubernetes API / events arrive. Typically docker events are much faster than k8s API calls. We will need a few days to fix it, making the docker part `Kubernetes aware`. 

I still believe using the ENV var LOGS_ENABLED=true for the containers, you want to collect logs from should work. Maybe it helps as a workaround until the `sematext.com/logs-enabled=true` k8s annotations work.   

Can you please confirm that you use docker as container runtime? Or cri-o with containerd? 

We can also have a support call, please give us your contact in Sematext chat.

**Comment by dabeck** [comment]
Great, thanks for your quick response ✌️
Since we're only running in k8s and are only able to set the ENV-Var within the k8s deployment/pod definition this is not working properly.
I'm absolutly sure we're running on docker 18.06

**Comment by megastef** [comment]
@dabeck did you try the latest Logagent version? The issue should be fixed.

**Comment by dabeck** [comment]
Works like a charm. Many thanks 😊

**Comment by dabeck** [comment]
Too happy too soon. Unfortunately I've not investigated enough and it does actually NOT work well. Even though it logs the proper annotation values it still logs every container to sematext AND the `LOGSENE_ENABLED_DEFAULT`/`LOGS_ENABLED_DEFAULT` is completly ignored.

**Comment by dabeck** [comment]
Too happy too soon. Unfortunately I've not investigated enough and it does actually NOT work well. Even though it logs the proper annotation values it still logs every container to sematext AND the `LOGSENE_ENABLED_DEFAULT`/`LOGS_ENABLED_DEFAULT` is completly ignored.

**Comment by adnanrahic** [comment]
Hey @dabeck!

I've created a fix for this issue. 

I'm still not sure if it works with your use-case. Can you check it out and verify the fix is working by using the `sematext/logagent:dev` image?

I've tested it out by using the LOGS_ENABLED and LOGS_ENABLED_DEFAULT environment variables with Docker Compose and Docker Stack.

**Comment by adnanrahic** [comment]
After another day of testing a Kubernetes setup, I've pushed another fix and tested whitelisting containers.

To enable whitelisting in a Kubernetes cluster you need to set the `LOGS_ENABLED_DEFAULT=false` environment variable on the Logagent Daemonset. While setting `"sematext.com/logs-enabled": "true"` in the Pod annotation of the Pod you want to ship logs for.

`helm ... -set logagent.config.LOGS_ENABLED_DEFAULT=false` should also work when using Helm, as long as you use the `"sematext.com/logs-enabled": "true"` Pod annotations for the Pods you want to ship logs from.

This feature is currently fixed in the `sematext/logagent:dev` image. I'll merge this fix and release an official version today.

**Comment by adnanrahic** [comment]
Update:

Hey @dabeck! I've released a new version with these fixes. You can get them by using either the `latest` or `3.0.31` tag. The Helm chart is configured to pull the `latest` version of Logagent. To make sure you are running the latest version of Logagent, the stdout of the Logagent container should have `[3.0.31]` in the log lines.

Running the same Helm command should do the trick. :smile: 
```bash
helm ... -set logagent.config.LOGS_ENABLED_DEFAULT=false
```

Here are sample Gists that worked for me:

- [Logagent Daemonset](https://gist.github.com/adnanrahic/3300210811d4bfab11a4e61665458319)

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sematext-logagent
  labels:
    app: sematext-logagent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sematext-logagent
subjects:
- kind: ServiceAccount
  name: sematext-logagent
  namespace: default
---
# Cluster Role for Logagent
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sematext-logagent
  labels:
    app: sematext-logagent
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods
  verbs:
  - list
  - get
  - watch
---
# Service Account for Logagent
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sematext-logagent
  labels:
    app: sematext-logagent
---
# Daemonset
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: st-logagent
spec:
  selector:
   matchLabels:
     app: st-logagent
  template:
    metadata:
      labels:
        app: st-logagent
    spec:
      nodeSelector: {}
      serviceAccountName: sematext-logagent
      hostNetwork: true
      dnsPolicy: "ClusterFirst"
      restartPolicy: "Always"
      containers:
      - name: sematext-logagent
        image: sematext/logagent:latest
        imagePullPolicy: "Always"
        env:
          - name: LOGS_TOKEN
            value: "token"
          - name: REGION
            value: "US/EU"
          - name: USE_LOGS_ENABLED_K8S_ANNOTATIONS
            value: "true"
          - name: LOGS_ENABLED_DEFAULT
            value: "false"
          # either will work
          # - name: LOGSENE_ENABLED_DEFAULT
          #   value: "false"
          # for debugging enable -v
          # - name: LOGAGENT_ARGS
          #   value: "-v"
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
          - mountPath: /etc/localtime
            name: localtime
#          - mountPath: /etc/logagent
#            name: patterns
        securityContext:
          privileged: true
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: localtime
          hostPath:
            path: /etc/localtime
#        - name: patterns
#          configMap:
#            name: sematext-agent-patterns
#            items:
#            - key: patterns.yml
#              path: patterns.yml
```


- [Pod Deployment](https://gist.github.com/adnanrahic/9fed9c64ac2ca796c78dda58e483a4fa)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: app
  name: app
spec:
  selector:
    matchLabels:
      service: app
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        "sematext.com/logs-enabled": "true"
      creationTimestamp: null
      labels:
        service: app
    spec:
      containers:
        image: image_name
        name: app
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
```

**Comment by dabeck** [comment]
Hey, sorry for the late response. We've just upgraded to 3.0.31.
It does indeed just log my annotated containers but it also logs eg. `kubelet` containers as well. Those "system" containers are not managed by k8s because they actually are k8s 😁 

```
"root":{
"@timestamp":"2020-04-08T07:38:07.105Z"
"message":"E0408 07:38:07.104947 3222 kubelet_volumes.go:154] Orphaned pod "05f81738-7ca5-4099-90cc-3b1b6b48a92b" found, but volume paths are still present on disk : There were a total of 3 errors similar to this. Turn up verbosity to see them."
"severity":"info"
"os":{
"host":"az1-dev-worker1.novalocal"
}
"logSource":"rancher/hyperkube:v1.15.11-rancher1_kubelet_6d90fbd5df14"
"container":{
"id":"6d90fbd5df14d27a895415b23570bbd387f725a9ce245a9382ed61b18cce2bb2"
"type":"docker"
"name":"kubelet"
"image":{...}
"host":{...}
}
"@timstamp":"2020-04-08T07:38:07.105Z"
"@timestamp_received":"2020-04-08T07:38:09.378Z"
"logsene_orig_type":"logs"
}
```

**Comment by adnanrahic** [comment]
Awesome! I'm glad we finally ironed out this bug. It has been harassing me for a month. :smile: 

Feel free to reach out if you have any more suggestions or if you see any bugs.

**Comment by dabeck** [comment]
OK, but could you give me some insights why those "non managed" containers still get logged?!

**Comment by adnanrahic** [comment]
Are you still using this setup?

```
Cloud platform: OpenStack
K8s: rke (Rancher Kubernetes Engine) deployed k8s Cluster v1.14.9
Docker: 18.06.3-ce
```

I've tested it out with Minkube and a managed Kubernetes cluster on DigitalOcean, which is just a standard Kubernetes cluster under the hood. It did not log anything from the `kube-system` namespace.

Maybe this is some specific behavior for Rancher? :thinking: 

I'm not aware of what the difference is between them. Could you open up another issue explaining this and I'll debug the issue first chance I get?

One last thing that might fix it is the cluster role you have attached to the Logagent container. If you only give it permission to read logs from the `default` namespace, you can totally avoid Kubernetes system containers. It's something else I'll need to debug once I tackle debugging Rancher as well. :smile: 

If you can, please do try deploying the Logagent daemonset without using Helm but with `kubectl`. I just want to rule out the option that one might work but the other does not.

**Comment by dabeck** [comment]
OK thank you, yes we're still using this setup.
I'm a little under pressure right now but will give it a try later.
